@URL = https://localhost:7233
@Token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiUmFtIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIyIiwiZXhwIjoxNzYzMTE3MzA2LCJpc3MiOiJKd3RUb2tlbiIsImF1ZCI6Ikp3dFRva2VuIn0.A-JNsgyrqyW6Me32PUc6-25HDBcycXlSnKrtg7uPaZSwjbqP2ciBrTKBGFp8M55jykt5QtG5ZlVuE8oHGNMO5Q

###Register api
POST {{URL}}/api/Auth/Register
Accept: application/json
Content-Type: application/json
{
  "UserName": "Sita",
  "Password": "Sita123"
}

###Login api
POST {{URL}}/api/Auth/Login
Accept: application/json
Content-Type: application/json
{
  "UserName": "Ram",
  "Password": "Ram123"
}

### Get all user
GET {{URL}}/api/User?page=1&pageSize=5&sortBy=username&sortOrder=desc&word=
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiSGFycnkiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJleHAiOjE3NjMxMTY3NzIsImlzcyI6Ikp3dFRva2VuIiwiYXVkIjoiSnd0VG9rZW4ifQ.U6qbG5Xbuvnmelgq0eqp5XuJaGmTWvUs-T3hP_qA4wQlHUO4m-H8O-0bv1FgHq87J2uv7QHOeLFAAFSJ4SOcqA


### Get user by id 
GET {{URL}}/api/User/1
Accept: application/json
Authorization: Bearer {{Token}}

### Get user by id
DELETE {{URL}}/api/User/1
Accept: application/json
Authorization: Bearer {{Token}}

### Update user 
PUT {{URL}}/api/User/2
Accept: application/json
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "UserName": "Ram",
  "Password": "Ram@gmail.com"
}

